student/auth.py
from flask import request,render_template,redirect,flash,Blueprint,url_for,session
from .forms import LoginForm,RegisterForm,AdminLogin
from werkzeug.security import generate_password_hash,check_password_hash
from . import db

auth = Blueprint('auth',__name__)


@auth.route('/', methods = ['GET', 'POST'])
def login():
    
    c  =  db.connection.cursor()
    forms = LoginForm()
    if forms.validate_on_submit() or request.method == 'POST':

        email = forms.email.data
        password = forms.password.data
        query = """SELECT password FROM student.student WHERE email = %s"""
        c.execute(query,(email,))
        pass_word = c.fetchone()
        if pass_word and check_password_hash(pass_word["password"], password) :

            c.execute("""SELECT id FROM student.student WHERE email = %s""",(email,))
            idn  =  c.fetchone()
            flash('Logged in Successfully',category="success")
            session['id']=idn['id']
            #login_user(idn['id'])
            return redirect(url_for("views.view",idn = idn["id"]))

        else: 
            flash("Invalid Email or Password",category="error")
        c.close()

    return render_template('login.html',title = 'loginpage',form = forms)

@auth.route('/register',methods = [ 'POST','GET'])
def register():
    forms = RegisterForm()
    c = db.connection.cursor()
    if forms.validate_on_submit() or request.method == "POST":

        email = forms.email.data
        password = forms.password.data
        query = """SELECT id FROM student.student WHERE email = %s"""
        c.execute(query,(email,))
        id1  =  c.fetchone()

        if id1:
            flash("Email Id already exists",category="error")
        else:

            query = """INSERT INTO student.student (email,password) VALUES (%s, %s)"""
            c.execute(query,(email,generate_password_hash(password),))
            db.connection.commit()
            c.execute("""SELECT id FROM student.student WHERE email = %s""",(email,))
            idn = c.fetchone()
            session['id']=idn['id']
            #login_user(idn['id'])
            flash('Fill this form to complete your registration',category='success')
            return redirect(url_for("views.edit",idn = idn['id']))
        c.close()
        
    return render_template('register.html',title = 'register',form = forms)

@auth.route('/admin/',methods=['POST', 'GET'])
def admin():
    form = AdminLogin()
    if request.method == 'POST' or form.validate_on_submit():
        email=form.userid.data
        password=form.password.data
        if email == "admin123@gmail.com" and password == 'admin123ispassword':
            session['id']='Admin'
            flash('Login Sucessfull',category='success')
            return redirect(url_for('views.full'))
        else:
            flash('Invalid userid or password',category='error')
    return render_template('adminlogin.html',title='admin',form=form)

@auth.route('/logout',methods=[ 'POST', 'GET']) 
def logout():
    session.pop('id', None)
    flash("You have been logged out sucessfully.....",category='success')
    return redirect(url_for('auth.login'))

@auth.route('/adminlogout',methods=[ 'POST', 'GET']) 
def adminlogout():
    session.pop('id', None)
    flash("You have been logged out sucessfully.....",category='success')
    return redirect(url_for('auth.admin'))



student/templates/admin.html
{% extends 'index.html'%}
{% block content %}
<ul class="nav justify-content-end">
    <li class="nav-item">
      <a class="nav-link active" href="{{url_for('auth.adminlogout')}}">Logout</a>
    </li>
</ul>
<form method="POST" action="">
    <style>
        h1{text-align: center;}
        table, th, td {
            border: 1px solid black;
        }
    </style>
    <h1>Students Details</h1>
    
    <table style="width:100%">
        <tr>
          <th>Regno</th>
          <th>Name</th> 
          <th>Parent/Guardian Name</th>
          <th>Age</th>
          <th>DOB</th> 
          <th>Department</th>
          <th>Present Semester</th>
          <th>Avereage GPA</th> 
          <th>Phone</th>
          <th>Address</th>
          <th>City</th> 
          <th>State</th>
          <th>PIN</th>
        </tr>
        {% for forms in form %}
            <tr>
            <td>{{forms['regno']}}</td>
            <td>{{forms['name']}}</td>
            <td>{{forms['parentname']}}</td>
            <td>{{forms['age']}}</td>
            <td>{{forms['DOB']}}</td>
            <td>{{forms['department']}}</td>
            <td>{{forms['presentsem']}}</td>
            <td>{{forms['avggpa']}}</td>
            <td>{{forms['phonenum']}}</td>
            <td>{{forms['address']}}</td>
            <td>{{forms['city']}}</td>
            <td>{{forms['state']}}</td>
            <td>{{forms['PIN']}}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
    <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputRegno">Enter Registration Number To Delete Details</label>
          <input type="text" class="form-control" name='stdregno' id="inputRegno" placeholder="Registration Number">
        </div>
    </div>
    <div class="form-group">
        <input class="btn btn-outline-info" id="sign" name="sign" type="submit" value="Delete">
    </div>
</form>
{% endblock %}

student/templates/adminlogin.html
{% extends 'index.html' %}
{% block content %}
<ul class="nav justify-content-end">
    <li class="nav-item">
      <a class="nav-link active" href="{{url_for('auth.login')}}">LOGIN HERE(Non-Admin's)</a>
    </li>
  </ul>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="boarder-bottom nb-4">Admin's Login Page</legend>
                <div class="form-group">
                    {{form.userid.label(class='form-control-label')}}
                    {% if form.userid.errors %}
                        {{form.userid(class='form-control form-control-lg is-invalid')}}
                        <div class='invalid-feedback'>
                            {% for error in form.userid.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.userid(class='form-control form-control-lg')}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.password.label(class='form-control-label')}}
                    {% if form.password.errors %}
                        {{form.password(class='form-control form-control-lg is-invalid')}}
                        <div class='invalid-feedback'>
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.password(class='form-control form-control-lg')}}
                    {% endif %}
                </div>
            </fieldset>
            </br>
            <div class="form-group">
                {{form.signin(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
{% endblock %}

student/templates/edit.html
{% extends 'index.html' %}
{% block content %}
<form method="POST" action="">
    <!--Student Details-->
    <legend class="boarder-bottom nb-4">Student Details</legend>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputRegno">Registration Number</label>
        <input type="text" class="form-control" name='stdregno' id="inputRegno" placeholder="Registration Number" required>
      </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputName">Name</label>
          <input type="text"  name='stdname' class="form-control" id="inputName" placeholder="Name" required>
        </div>
        <div class="form-group col-md-6">
          <label for="inputParentName">Parent/Guardian Name</label>
          <input type="text"  name='stdpname' class="form-control" id="inputParentName" placeholder="Parent/Gaurdian Name" required>
        </div>
        <div class="form-group col-md-6">
          <label for="inputAge">Age</label>
          <input type="number"  name='stdage'class="form-control" id="inputAge" placeholder="Age" min="1" max="50" required>
        </div>
        <div class="form-group col-md-6">
          <label for="inputLastName">DOB</label>
          <input type="date"  name='stddob' class="form-control" id="inputDOB" placeholder="DOB" required>
        </div>
    </div>

    <!--Education details-->
    <legend class="boarder-bottom nb-4">Student Details</legend>
    <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputDepartment">Department</label>
          <input type="text"  name='stddept' class="form-control" id="inputDepartment" placeholder="Department" required>
        </div>
        <div class="form-group col-md-6">
            <label for="inputSemester">PresentSemester</label>
            <input type="number"  name='stdpresem' class="form-control" id="inputSemester" placeholder="PresentSemester"  required>
        </div>
        <div class="form-group col-md-6">
          <label for="inputAverageGPA">Avg.GPA</label>
          <input type="text"  name='stdavgpa' class="form-control" id="inputAverageGPA" placeholder="Average GPA" maxlength="3" required>
        </div>
    </div>

    <!--For Entering the Contact details-->
    <legend class="boarder-bottom nb-4">Contact Details</legend>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputPhoneNumber">Phone</label>
            <input type="tel"  name='stdphone' class="form-control" id="inputPhoneNumber" placeholder="PhoneNumber" minlength="10" maxlength="10" required>
          </div>
    </div>
    <div class="form-group">
        <label for="inputAddress1">Address</label>
        <input type="text" name='stdaddres' class="form-control" id="inputAddress" placeholder="Adress" required>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputCity">City</label>
        <input type="text"  name='stdcity' class="form-control" id="inputCity" placeholder="City" required>
      </div>
      <div class="form-group col-md-6">
        <label for="inputCity">State</label>
        <input type="text"  name='stdstate' class="form-control" id="inputCity" placeholder="State" required>
      </div>
      <div class="form-group col-md-2">
        <label for="inputZip">PIN</label>
        <input type="text"  name='stdpin' class="form-control" id="inputZip" maxlength="6" required>
      </div>
    </div>

    <div class="form-group">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="gridCheck" required>
        <label class="form-check-label" for="gridCheck">
          The above given informations are correct accourding to my knowledge
        </label>
      </div>
    </div>
    <button type="submit" class="btn btn-primary ">Save</button>
</form>
{% endblock %}

student/templates/index.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
        <title>{{title|upper}}</title>
    {% endif %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<div class="container">
    {% with messages = get_flashed_messages(category==true) %}
        {% if messages %}
            {% for message in messages %}
                {% if category == "error" %}
                    <div class="alert alert-danger alert-dismissable fade show" role="alert" >
                        {{message}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% elif  category == "warning" %}
                    <div class="alert alert-warning alert-dismissable fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% else %}
                    <div class="alert alert-success alert-dismissable fade show" role="alert">
                        {{message}}
                        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif%}
    {% endwith %}

    {% block content %}

    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" 
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</div>
</body>

student/templates/login.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="content-section">
        <form method="POST" action="">
            {{form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="boarder-bottom nb-4">Login</legend>
                <div class="form-group">
                    {{form.email.label(class='form-control-label')}}
                    {% if form.email.errors %}
                        {{form.email(class='form-control form-control-lg is-invalid')}}
                        <div class='invalid-feedback'>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class='form-control form-control-lg')}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.password.label(class='form-control-label')}}
                    {% if form.password.errors %}
                        {{form.password(class='form-control form-control-lg is-invalid')}}
                        <div class='invalid-feedback'>
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.password(class='form-control form-control-lg')}}
                    {% endif %}
                </div>
            </fieldset>
            <br>
            <div class="form-group">
                {{form.signin(class="btn btn-outline-info")}}
            </div>
            <br>
            <small class="text-mutated ml-2">
                <a href="#">Forgot Password</a>
            </small>
        </form>
    </div>
    <div class="boarder-top pt-3">
        <small class="text-muted">
            Create an account? <a class="ml-2" href="{{url_for('auth.register')}}">Sign UP</a>
        </small>
    </div>
</div>
{% endblock %}

student/templates/register.html
{% extends 'index.html' %}
{% block content%}
<div class="container">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag()}}
            <fieldset class="form-group">
                <legend class="boarder-bottom nb-4">Join</legend>
                <div class="form-group">
                    {{form.email.label(class='form-control-label')}}
                    {% if form.email.errors %}
                        {{form.email(class='form-control form-control-lg is-invalid')}}
                        <div class='invalid-feedback'>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class='form-control form-control-lg')}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.password.label(class='form-control-label')}}
                    {% if form.password.errors %}
                        {{form.password(class='form-control form-control-lg is-invalid')}}
                        <div class='invalid-feedback'>
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.password(class='form-control form-control-lg')}}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{form.confirm.label(class='form-control-label')}}
                    {% if form.confirm.errors %}
                        {{form.confirm(class='form-control form-control-lg is-invalid')}}
                        <div class='invalid-feedback'>
                            {% for error in form.confirm.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.confirm(class='form-control form-control-lg')}}
                    {% endif %}
                </div>
            </fieldset>
            <br>
            <div class="form-group">
                {{form.signup(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
    <div class="boarder-top pt-3">
        <small class="text-muted">
            Already have an account?<a class="ml-2" href="{{url_for('auth.login')}}">Sign In</a>
        </small>
    </div>
</div>
{% endblock %}

student/templates/sedit.html
{% extends 'index.html' %}
{% block content %}

<ul class="nav justify-content-end">
    <li class="nav-item">
      <a class="nav-link active" href="{{url_for('auth.logout')}}">Logout</a>
    </li>
</ul>
<form method="POST" action="">
    <!--Student Details-->
    <legend class="boarder-bottom nb-4">Student Details</legend>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputRegno">Registration Number</label>
        <input type="text" class="form-control" name='stdregno' id="inputRegno" value="{{form['regno']}}" readonly>
      </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputName">Name</label>
          <input type="text" class="form-control" name='stdname' id="inputName" value="{{form['name']}}" readonly>
        </div>
        <div class="form-group col-md-6">
          <label for="inputParentName">Parent/Gaurdian Name</label>
          <input type="text" class="form-control" name='stdpname'id="inputLastName" value="{{form['parentname']}}" readonly>
        </div>
        <div class="form-group col-md-6">
          <label for="inputAge">Age</label>
          <input type="number" class="form-control" name="stdage" id="inputAge" value="{{form['age']}}" reaonlyd>
        </div>
        <div class="form-group col-md-6">
          <label for="inputLastName">DOB</label>
          <input type="date" class="form-control" name="stddob" id="inputDOB" value="{{form['DOB']}}" readonly>
        </div>
    </div>

    <!--Education details-->
    <legend class="boarder-bottom nb-4">Student Details</legend>
    <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputDepartment">Department</label>
          <input type="text" class="form-control" name="stddept" id="inputDepartment" value="{{form['department']}}" required>
        </div>
        <div class="form-group col-md-6">
            <label for="inputSemester">PresentSemester</label>
            <input type="number" class="form-control" name="presem" id="inputSemester" value="{{form['presentsem']}}"  required>
        </div>
        <div class="form-group col-md-6">
          <label for="inputAverageGPA">Avg.GPA</label>
          <input type="text" class="form-control" name="stdavgpa" id="inputAverageGPA" value="{{form['avggpa']}}" maxlength="3" required>
        </div>
    </div>

    <!--For Entering the Contact details-->
    <legend class="boarder-bottom nb-4">Contact Details</legend>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputPhoneNumber1">Phone</label>
            <input type="tel" class="form-control" id="inputPhoneNumber" value="{{form['phonenum']}}" readonly>
          </div>
    </div>
    <div class="form-group">
        <label for="inputAddress1">Address</label>
        <input type="text" class="form-control" name='stdaddres' id="inputAddress" value="{{form['address']}}" required>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputCity">City</label>
        <input type="text" class="form-control" name='stdcity' id="inputCity" value="{{form['city']}}" required>
      </div>
      <div class="form-group col-md-6">
        <label for="inputCity">State</label>
        <input type="text" class="form-control" name='stdstate' id="inputCity" value="{{form['state']}}" required>
      </div>
      <div class="form-group col-md-2">
        <label for="inputZip">PIN</label>
        <input type="text" class="form-control" name='stdpin' id="inputZip" value="{{form['PIN']}}" required>
      </div>
    </div>

    <div class="form-group">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="gridCheck" required>
        <label class="form-check-label" for="gridCheck">
          The above given informations are correct accourding to my knowledge
        </label>
      </div>
    </div>
    <button type="submit" class="btn btn-primary ">Save</button>
</form>
{% endblock %}

student/templates/view.html
{% extends 'index.html' %}
{% block content %}
<ul class="nav justify-content-end">
    <li class="nav-item">
      <a class="nav-link active" href="{{url_for('auth.logout')}}">Logout</a>
    </li>
</ul>
<form method="POST" action="">
    <!--Student Details-->
    <legend class="boarder-bottom nb-4">Student Details</legend>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputRegno">Registration Number</label>
        <input type="text" class="form-control" id="inputRegno" value="{{form['regno']}}" readonly>
      </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputName">Name</label>
          <input type="text" class="form-control" id="inputName" value="{{form['name']}}" readonly>
        </div>
        <div class="form-group col-md-6">
          <label for="inputParentName">Parent/Gaurdian Name</label>
          <input type="text" class="form-control" id="inputLastName" value="{{form['parentname']}}" readonly>
        </div>
        <div class="form-group col-md-6">
          <label for="inputAge">Age</label>
          <input type="number" class="form-control" id="inputAge" value="{{form['age']}}" readonly>
        </div>
        <div class="form-group col-md-6">
          <label for="inputLastName">DOB</label>
          <input type="date" class="form-control" id="inputDOB" value="{{form['DOB']}}" readonly>
        </div>
    </div>

    <!--Education details-->
    <legend class="boarder-bottom nb-4">Student Details</legend>
    <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputDepartment">Department</label>
          <input type="text" class="form-control" id="inputDepartment" value="{{form['department']}}" readonly>
        </div>
        <div class="form-group col-md-6">
            <label for="inputSemester">PresentSemester</label>
            <input type="number" class="form-control" id="inputSemester" value="{{form['presentsem']}}" min="1" max="8" readonly>
        </div>
        <div class="form-group col-md-6">
          <label for="inputAverageGPA">Avg.GPA</label>
          <input type="text" class="form-control" id="inputAverageGPA" value="{{form['avggpa']}}" maxlength="3" readonly>
        </div>
    </div>

    <!--For Entering the Contact details-->
    <legend class="boarder-bottom nb-4">Contact Details</legend>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputPhoneNumber1">Phone</label>
            <input type="tel" class="form-control" id="inputPhoneNumber" value="{{form['phonenum']}}" readonly>
          </div>
    </div>
    <div class="form-group">
        <label for="inputAddress1">Address</label>
        <input type="text" class="form-control" id="inputAddress" value="{{form['address']}}" readonly>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputCity">City</label>
        <input type="text" class="form-control" id="inputCity" value="{{form['city']}}" readonly>
      </div>
      <div class="form-group col-md-6">
        <label for="inputCity">State</label>
        <input type="text" class="form-control" id="inputCity" value="{{form['state']}}" readonly>
      </div>
      <div class="form-group col-md-2">
        <label for="inputZip">PIN</label>
        <input type="text" class="form-control" id="inputZip" value="{{form['PIN']}}" readonly>
      </div>
    </div>
    <button type="submit" class="btn btn-primary justify-content-end">Edit</button>
</form>
{% endblock %}